name: Build simple server

# workflow를 실행시키는 이벤트 정의
# main 브런치에 push할 때 실행
on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 작업을 수행하기 위해 Runner에 소스 코드를 가져오는 부분
      - name: Checkout
        uses: actions/checkout@v3
    
      # ECR에 접근하기 위해 AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      # ECR에 대해 Docker 클라이언트 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Docker Image Build and Push to Amazon ECR
        env:
          ECR_REPOSITORY: simple-server
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: 0.1.0
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
