name: Build simple server

# workflow를 실행시키는 이벤트 정의
# main 브런치에 push할 때 실행
on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: simple-server
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 작업을 수행하기 위해 Runner에 소스 코드를 가져오는 부분
      - name: Checkout
        uses: actions/checkout@v3
    
      # ECR에 접근하기 위해 AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      # ECR에 대해 Docker 클라이언트 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Docker Image Build and Push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.0.0
        
      - name: Checkout kustomize repository
        uses: actions/checkout@v3
        with:
          repository: min-chocopie/cd-simple-server
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: cd-simple-server
      
      - name: Update Kubernetes resources
        env: 
          IMAGE: 767791266862.dkr.ecr.ap-northeast-2.amazonaws.com/simple-server
        run: |
          cd cd-simple-server/overlays/dev
          kustomize edit set image ${{ env.IMAGE }}=${{ env.IMAGE }}:${{ github.sha }}
      
      - name: Commit files
        run: |
          cd cd-simple-server
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin main
